"""1.3.6

Revision ID: 329f9007d7ff
Revises: 4b38791cf799
Create Date: 2024-10-14 15:22:54.705085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329f9007d7ff'
down_revision = '4b38791cf799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_USER_INFO_STATS") as batch_op:
            batch_op.add_column(sa.Column('LAST_SEEN', sa.Text, nullable=True))
    except Exception as e:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SITE_USER_INFO_STATS', 'LAST_SEEN')
    # ### end Alembic commands ###
