"""1.3.7

Revision ID: 34d0fce12d1c
Revises: 329f9007d7ff
Create Date: 2026-03-13 09:24:31.507866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d0fce12d1c'
down_revision = '329f9007d7ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SEARCH_RESULT_INFO") as batch_op:
            batch_op.add_column(sa.Column('HR', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('HR_DAYS', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('FREE_DEADLINE', sa.Text(), nullable=True))
    except Exception:
        # 兼容已有手工修改或重复执行迁移的情况
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SEARCH_RESULT_INFO") as batch_op:
            batch_op.drop_column('FREE_DEADLINE')
            batch_op.drop_column('HR_DAYS')
            batch_op.drop_column('HR')
    except Exception:
        pass
    # ### end Alembic commands ###
