#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask ${UMASK}

if [ -f ${NASTOOL_CONFIG} ]; then
    # NT_PORT=$(yq '.app.web_port' /config/config.yaml)
    NT_PORT=$(python3 -c "import yaml; c=yaml.safe_load(open('/config/config.yaml')); print((c or {}).get('app',{}).get('web_port', 3000))" 2>/dev/null)
    NT_PORT=${NT_PORT:-3000}
else
    NT_PORT=3000
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${NT_PORT}" \
    cd ${WORKDIR} s6-setuidgid nt python3 run.py